services:
  - type: web
    name: hexlet-ai-for-devs-386-backend
    runtime: docker
    dockerfilePath: ./docker/backend.Dockerfile
    healthCheckPath: /api/v1/health
    port: 8000
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: calcom
      - key: APP_VERSION
        value: "0.1.0"
